import { Hono, type Context } from 'hono';
import type { AppEnv, AuthUser } from '../types.js';
import { authMiddleware } from '../middleware/auth.js';
import { requireCampaignMember } from '../lib/access.js';
import type {
  NoteFolder,
  Note,
  NoteScope,
  CreateNoteFolderInput,
  UpdateNoteFolderInput,
  CreateNoteInput,
  UpdateNoteInput,
  ReorderNotesInput,
} from '@anvil/types';

export const noteRoutes = new Hono<AppEnv>();

noteRoutes.use('/*', authMiddleware);
noteRoutes.use('/:campaignId/*', async (c, next) => {
  const user = c.get('user') as AuthUser;
  const accessError = await requireCampaignMember(c, c.req.param('campaignId'), user);
  if (accessError) return accessError;
  await next();
});

// ── Row Types & Mappers ──

interface NoteFolderRow {
  id: string;
  campaign_id: string;
  user_id: string;
  scope?: NoteScope | null;
  parent_folder_id: string | null;
  name: string;
  is_auto_generated: number;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

function rowToFolder(row: NoteFolderRow): NoteFolder {
  return {
    id: row.id,
    campaignId: row.campaign_id,
    userId: row.user_id,
    scope: row.scope === 'director' ? 'director' : 'player',
    parentFolderId: row.parent_folder_id,
    name: row.name,
    isAutoGenerated: row.is_auto_generated === 1,
    sortOrder: row.sort_order,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

interface NoteRow {
  id: string;
  campaign_id: string;
  user_id: string;
  scope?: NoteScope | null;
  folder_id: string;
  title: string;
  content: string;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

function rowToNote(row: NoteRow): Note {
  return {
    id: row.id,
    campaignId: row.campaign_id,
    userId: row.user_id,
    scope: row.scope === 'director' ? 'director' : 'player',
    folderId: row.folder_id,
    title: row.title,
    content: row.content,
    sortOrder: row.sort_order,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// ── Auto-seed Helpers ──

async function ensureAutoFolders(
  db: D1Database,
  campaignId: string,
  userId: string,
  scope: NoteScope,
): Promise<void> {
  const existing = await db
    .prepare(
      'SELECT COUNT(*) as count FROM note_folders WHERE campaign_id = ? AND user_id = ? AND scope = ? AND is_auto_generated = 1',
    )
    .bind(campaignId, userId, scope)
    .first<{ count: number }>();

  if (existing && existing.count >= 2) return;

  const folders = [
    { name: 'Session Notes', sortOrder: 0 },
    { name: 'World Notes', sortOrder: 1 },
  ];

  const stmts = folders.map((f) =>
    db
      .prepare(
        `INSERT OR IGNORE INTO note_folders (id, campaign_id, user_id, scope, name, is_auto_generated, sort_order)
         VALUES (?, ?, ?, ?, ?, 1, ?)`,
      )
      .bind(crypto.randomUUID(), campaignId, userId, scope, f.name, f.sortOrder),
  );
  await db.batch(stmts);
}

async function getAllowedScopes(
  c: Context<AppEnv>,
  campaignId: string,
  user: AuthUser,
): Promise<NoteScope[]> {
  const row = await c.env.DB.prepare(
    `SELECT c.director_id, cm.role
     FROM campaigns c
     JOIN campaign_members cm ON cm.campaign_id = c.id AND cm.user_id = ?
     WHERE c.id = ? AND c.deleted_at IS NULL`,
  )
    .bind(user.id, campaignId)
    .first<{ director_id: string; role: string }>();

  if (!row) return [];
  if (row.director_id === user.id || row.role === 'director') return ['director', 'player'];
  return ['player'];
}

async function resolveScope(
  c: Context<AppEnv>,
  campaignId: string,
  user: AuthUser,
  requested?: string | null,
): Promise<NoteScope | Response> {
  const allowedScopes = await getAllowedScopes(c, campaignId, user);
  const preferred = requested === 'director' || requested === 'player' ? requested : null;
  const fallback = allowedScopes.includes(user.role) ? user.role : allowedScopes[0];
  const scope = preferred ?? fallback;
  if (!scope || !allowedScopes.includes(scope)) {
    return c.json({ error: 'Forbidden note scope' }, 403);
  }
  return scope;
}

function isResponse(value: NoteScope | Response): value is Response {
  return value instanceof Response;
}

// List available note scopes for this campaign/user.
noteRoutes.get('/:campaignId/note-scopes', async (c) => {
  const campaignId = c.req.param('campaignId');
  const user = c.get('user') as AuthUser;
  const scopes = await getAllowedScopes(c, campaignId, user);
  const defaultScope = scopes.includes(user.role) ? user.role : scopes[0] ?? 'player';
  return c.json({ scopes, defaultScope });
});

// ── Folder Routes ──

// List folders
noteRoutes.get('/:campaignId/note-folders', async (c) => {
  const campaignId = c.req.param('campaignId');
  const user = c.get('user') as AuthUser;
  const scope = await resolveScope(c, campaignId, user, c.req.query('scope'));
  if (isResponse(scope)) return scope;

  await ensureAutoFolders(c.env.DB, campaignId, user.id, scope);

  const results = await c.env.DB.prepare(
    'SELECT * FROM note_folders WHERE campaign_id = ? AND user_id = ? AND scope = ? ORDER BY sort_order ASC',
  )
    .bind(campaignId, user.id, scope)
    .all<NoteFolderRow>();

  return c.json({ folders: results.results.map(rowToFolder) });
});

// Create folder
noteRoutes.post('/:campaignId/note-folders', async (c) => {
  const campaignId = c.req.param('campaignId');
  const user = c.get('user') as AuthUser;
  const body = await c.req.json<CreateNoteFolderInput>();
  const scope = await resolveScope(c, campaignId, user, body.scope ?? c.req.query('scope'));
  if (isResponse(scope)) return scope;

  if (!body.name?.trim()) return c.json({ error: 'Name is required' }, 400);

  if (body.parentFolderId) {
    const parent = await c.env.DB.prepare(
      'SELECT id FROM note_folders WHERE id = ? AND campaign_id = ? AND user_id = ? AND scope = ?',
    )
      .bind(body.parentFolderId, campaignId, user.id, scope)
      .first();
    if (!parent) return c.json({ error: 'Parent folder not found' }, 404);
  }

  // Get the next sort order for this parent
  const maxOrder = await c.env.DB.prepare(
    `SELECT MAX(sort_order) as max_order FROM note_folders
     WHERE campaign_id = ? AND user_id = ? AND scope = ? AND parent_folder_id ${body.parentFolderId ? '= ?' : 'IS NULL'}`,
  )
    .bind(...[campaignId, user.id, scope, ...(body.parentFolderId ? [body.parentFolderId] : [])])
    .first<{ max_order: number | null }>();

  const id = crypto.randomUUID();
  const sortOrder = (maxOrder?.max_order ?? -1) + 1;

  await c.env.DB.prepare(
    'INSERT INTO note_folders (id, campaign_id, user_id, scope, parent_folder_id, name, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?)',
  )
    .bind(id, campaignId, user.id, scope, body.parentFolderId ?? null, body.name.trim(), sortOrder)
    .run();

  const row = await c.env.DB.prepare('SELECT * FROM note_folders WHERE id = ?')
    .bind(id)
    .first<NoteFolderRow>();
  if (!row) return c.json({ error: 'Failed to create folder' }, 500);

  return c.json({ folder: rowToFolder(row) }, 201);
});

// Update folder
noteRoutes.patch('/:campaignId/note-folders/:folderId', async (c) => {
  const campaignId = c.req.param('campaignId');
  const folderId = c.req.param('folderId');
  const user = c.get('user') as AuthUser;
  const body = await c.req.json<UpdateNoteFolderInput>();

  const existing = await c.env.DB.prepare(
    'SELECT * FROM note_folders WHERE id = ? AND campaign_id = ? AND user_id = ?',
  )
    .bind(folderId, campaignId, user.id)
    .first<NoteFolderRow>();
  if (!existing) return c.json({ error: 'Not found' }, 404);

  // Guard: auto-generated folders cannot be renamed
  if (existing.is_auto_generated === 1 && body.name !== undefined) {
    return c.json({ error: 'Cannot rename auto-generated folders' }, 400);
  }

  const sets: string[] = [];
  const vals: unknown[] = [];

  if (body.name !== undefined) {
    sets.push('name = ?');
    vals.push(body.name.trim());
  }
  if (body.parentFolderId !== undefined) {
    if (body.parentFolderId) {
      const parent = await c.env.DB.prepare(
        'SELECT id FROM note_folders WHERE id = ? AND campaign_id = ? AND user_id = ? AND scope = ?',
      )
        .bind(body.parentFolderId, campaignId, user.id, existing.scope === 'director' ? 'director' : 'player')
        .first();
      if (!parent) return c.json({ error: 'Parent folder not found' }, 404);
    }
    sets.push('parent_folder_id = ?');
    vals.push(body.parentFolderId);
  }
  if (body.sortOrder !== undefined) {
    sets.push('sort_order = ?');
    vals.push(body.sortOrder);
  }

  if (sets.length === 0) return c.json({ error: 'No fields to update' }, 400);

  sets.push("updated_at = datetime('now')");
  vals.push(folderId);

  await c.env.DB.prepare(`UPDATE note_folders SET ${sets.join(', ')} WHERE id = ?`)
    .bind(...vals)
    .run();

  const row = await c.env.DB.prepare('SELECT * FROM note_folders WHERE id = ?')
    .bind(folderId)
    .first<NoteFolderRow>();
  if (!row) return c.json({ error: 'Not found' }, 404);

  return c.json({ folder: rowToFolder(row) });
});

// Delete folder
noteRoutes.delete('/:campaignId/note-folders/:folderId', async (c) => {
  const campaignId = c.req.param('campaignId');
  const folderId = c.req.param('folderId');
  const user = c.get('user') as AuthUser;

  const existing = await c.env.DB.prepare(
    'SELECT * FROM note_folders WHERE id = ? AND campaign_id = ? AND user_id = ?',
  )
    .bind(folderId, campaignId, user.id)
    .first<NoteFolderRow>();
  if (!existing) return c.json({ error: 'Not found' }, 404);

  if (existing.is_auto_generated === 1) {
    return c.json({ error: 'Cannot delete auto-generated folders' }, 400);
  }

  await c.env.DB.prepare('DELETE FROM note_folders WHERE id = ?').bind(folderId).run();
  return c.json({ ok: true });
});

// ── Note Routes ──

// List notes
noteRoutes.get('/:campaignId/notes', async (c) => {
  const campaignId = c.req.param('campaignId');
  const user = c.get('user') as AuthUser;
  const scope = await resolveScope(c, campaignId, user, c.req.query('scope'));
  if (isResponse(scope)) return scope;

  const results = await c.env.DB.prepare(
    'SELECT * FROM notes WHERE campaign_id = ? AND user_id = ? AND scope = ? ORDER BY sort_order ASC',
  )
    .bind(campaignId, user.id, scope)
    .all<NoteRow>();

  return c.json({ notes: results.results.map(rowToNote) });
});

// Search notes
noteRoutes.get('/:campaignId/notes/search', async (c) => {
  const campaignId = c.req.param('campaignId');
  const user = c.get('user') as AuthUser;
  const q = c.req.query('q');
  const scope = await resolveScope(c, campaignId, user, c.req.query('scope'));
  if (isResponse(scope)) return scope;

  if (!q?.trim()) return c.json({ notes: [] });

  const term = `%${q.trim()}%`;
  const results = await c.env.DB.prepare(
    'SELECT * FROM notes WHERE campaign_id = ? AND user_id = ? AND scope = ? AND (title LIKE ? OR content LIKE ?) ORDER BY updated_at DESC',
  )
    .bind(campaignId, user.id, scope, term, term)
    .all<NoteRow>();

  return c.json({ notes: results.results.map(rowToNote) });
});

// Create note
noteRoutes.post('/:campaignId/notes', async (c) => {
  const campaignId = c.req.param('campaignId');
  const user = c.get('user') as AuthUser;
  const body = await c.req.json<CreateNoteInput>();
  const scope = await resolveScope(c, campaignId, user, body.scope ?? c.req.query('scope'));
  if (isResponse(scope)) return scope;

  if (!body.title?.trim()) return c.json({ error: 'Title is required' }, 400);
  if (!body.folderId) return c.json({ error: 'Folder is required' }, 400);

  // Verify folder belongs to this user+campaign
  const folder = await c.env.DB.prepare(
    'SELECT id FROM note_folders WHERE id = ? AND campaign_id = ? AND user_id = ? AND scope = ?',
  )
    .bind(body.folderId, campaignId, user.id, scope)
    .first();
  if (!folder) return c.json({ error: 'Folder not found' }, 404);

  // Get the next sort order
  const maxOrder = await c.env.DB.prepare(
    'SELECT MAX(sort_order) as max_order FROM notes WHERE folder_id = ?',
  )
    .bind(body.folderId)
    .first<{ max_order: number | null }>();

  const id = crypto.randomUUID();
  const sortOrder = (maxOrder?.max_order ?? -1) + 1;

  await c.env.DB.prepare(
    'INSERT INTO notes (id, campaign_id, user_id, scope, folder_id, title, content, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
  )
    .bind(id, campaignId, user.id, scope, body.folderId, body.title.trim(), body.content ?? '', sortOrder)
    .run();

  const row = await c.env.DB.prepare('SELECT * FROM notes WHERE id = ?').bind(id).first<NoteRow>();
  if (!row) return c.json({ error: 'Failed to create note' }, 500);

  return c.json({ note: rowToNote(row) }, 201);
});

// Update note
noteRoutes.patch('/:campaignId/notes/:noteId', async (c) => {
  const campaignId = c.req.param('campaignId');
  const noteId = c.req.param('noteId');
  const user = c.get('user') as AuthUser;
  const body = await c.req.json<UpdateNoteInput>();

  const existing = await c.env.DB.prepare(
    'SELECT id, scope FROM notes WHERE id = ? AND campaign_id = ? AND user_id = ?',
  )
    .bind(noteId, campaignId, user.id)
    .first<{ id: string; scope: NoteScope | null }>();
  if (!existing) return c.json({ error: 'Not found' }, 404);

  const sets: string[] = [];
  const vals: unknown[] = [];

  if (body.title !== undefined) {
    sets.push('title = ?');
    vals.push(body.title.trim());
  }
  if (body.content !== undefined) {
    sets.push('content = ?');
    vals.push(body.content);
  }
  if (body.folderId !== undefined) {
    const folder = await c.env.DB.prepare(
      'SELECT id FROM note_folders WHERE id = ? AND campaign_id = ? AND user_id = ? AND scope = ?',
    )
      .bind(body.folderId, campaignId, user.id, existing.scope === 'director' ? 'director' : 'player')
      .first();
    if (!folder) return c.json({ error: 'Folder not found' }, 404);
    sets.push('folder_id = ?');
    vals.push(body.folderId);
  }
  if (body.sortOrder !== undefined) {
    sets.push('sort_order = ?');
    vals.push(body.sortOrder);
  }

  if (sets.length === 0) return c.json({ error: 'No fields to update' }, 400);

  sets.push("updated_at = datetime('now')");
  vals.push(noteId);

  await c.env.DB.prepare(`UPDATE notes SET ${sets.join(', ')} WHERE id = ?`)
    .bind(...vals)
    .run();

  const row = await c.env.DB.prepare('SELECT * FROM notes WHERE id = ?')
    .bind(noteId)
    .first<NoteRow>();
  if (!row) return c.json({ error: 'Not found' }, 404);

  return c.json({ note: rowToNote(row) });
});

// Delete note
noteRoutes.delete('/:campaignId/notes/:noteId', async (c) => {
  const campaignId = c.req.param('campaignId');
  const noteId = c.req.param('noteId');
  const user = c.get('user') as AuthUser;

  const existing = await c.env.DB.prepare(
    'SELECT id FROM notes WHERE id = ? AND campaign_id = ? AND user_id = ?',
  )
    .bind(noteId, campaignId, user.id)
    .first();
  if (!existing) return c.json({ error: 'Not found' }, 404);

  await c.env.DB.prepare('DELETE FROM notes WHERE id = ?').bind(noteId).run();
  return c.json({ ok: true });
});

// Batch reorder (folders + notes)
noteRoutes.put('/:campaignId/notes/reorder', async (c) => {
  const campaignId = c.req.param('campaignId');
  const user = c.get('user') as AuthUser;
  const body = await c.req.json<ReorderNotesInput>();

  if (!body.items?.length) return c.json({ error: 'No items to reorder' }, 400);

  const stmts: D1PreparedStatement[] = [];

  for (const item of body.items) {
    if (item.folderId !== undefined) {
      // This is a note being reordered/moved
      stmts.push(
        c.env.DB.prepare(
          "UPDATE notes SET sort_order = ?, folder_id = ?, updated_at = datetime('now') WHERE id = ? AND campaign_id = ? AND user_id = ?",
        ).bind(item.sortOrder, item.folderId, item.id, campaignId, user.id),
      );
    } else if (item.parentFolderId !== undefined) {
      // This is a folder being reordered/moved
      stmts.push(
        c.env.DB.prepare(
          "UPDATE note_folders SET sort_order = ?, parent_folder_id = ?, updated_at = datetime('now') WHERE id = ? AND campaign_id = ? AND user_id = ?",
        ).bind(item.sortOrder, item.parentFolderId, item.id, campaignId, user.id),
      );
    } else {
      // Just reorder (sort_order only)
      // Try notes first, then folders
      stmts.push(
        c.env.DB.prepare(
          "UPDATE notes SET sort_order = ?, updated_at = datetime('now') WHERE id = ? AND campaign_id = ? AND user_id = ?",
        ).bind(item.sortOrder, item.id, campaignId, user.id),
      );
      stmts.push(
        c.env.DB.prepare(
          "UPDATE note_folders SET sort_order = ?, updated_at = datetime('now') WHERE id = ? AND campaign_id = ? AND user_id = ?",
        ).bind(item.sortOrder, item.id, campaignId, user.id),
      );
    }
  }

  await c.env.DB.batch(stmts);
  return c.json({ ok: true });
});
