import type { Note, NoteFolder } from '@anvil/types';

export interface NoteFolderRow {
  id: string;
  campaign_id: string;
  user_id: string;
  parent_folder_id: string | null;
  name: string;
  is_auto_generated: number;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface NoteRow {
  id: string;
  campaign_id: string;
  user_id: string;
  folder_id: string;
  title: string;
  content: string;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export function rowToFolder(row: NoteFolderRow): NoteFolder {
  return {
    id: row.id,
    campaignId: row.campaign_id,
    userId: row.user_id,
    parentFolderId: row.parent_folder_id,
    name: row.name,
    isAutoGenerated: row.is_auto_generated === 1,
    sortOrder: row.sort_order,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export function rowToNote(row: NoteRow): Note {
  return {
    id: row.id,
    campaignId: row.campaign_id,
    userId: row.user_id,
    folderId: row.folder_id,
    title: row.title,
    content: row.content,
    sortOrder: row.sort_order,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export async function ensureAutoNoteFolders(
  db: D1Database,
  campaignId: string,
  userId: string,
): Promise<void> {
  const existing = await db
    .prepare(
      'SELECT COUNT(*) as count FROM note_folders WHERE campaign_id = ? AND user_id = ? AND is_auto_generated = 1',
    )
    .bind(campaignId, userId)
    .first<{ count: number }>();

  if (existing && existing.count >= 2) return;

  const folders = [
    { name: 'Session Notes', sortOrder: 0 },
    { name: 'World Notes', sortOrder: 1 },
  ];

  const stmts = folders.map((folder) =>
    db
      .prepare(
        `INSERT OR IGNORE INTO note_folders (id, campaign_id, user_id, name, is_auto_generated, sort_order)
         VALUES (?, ?, ?, ?, 1, ?)`,
      )
      .bind(crypto.randomUUID(), campaignId, userId, folder.name, folder.sortOrder),
  );
  await db.batch(stmts);
}

export async function getOwnedNoteFolder(
  db: D1Database,
  campaignId: string,
  userId: string,
  folderId: string,
): Promise<NoteFolderRow | null> {
  return db.prepare('SELECT * FROM note_folders WHERE id = ? AND campaign_id = ? AND user_id = ?')
    .bind(folderId, campaignId, userId)
    .first<NoteFolderRow>();
}

export async function getOwnedNote(
  db: D1Database,
  campaignId: string,
  userId: string,
  noteId: string,
): Promise<NoteRow | null> {
  return db.prepare('SELECT * FROM notes WHERE id = ? AND campaign_id = ? AND user_id = ?')
    .bind(noteId, campaignId, userId)
    .first<NoteRow>();
}

export async function assertOwnedNoteFolder(
  db: D1Database,
  campaignId: string,
  userId: string,
  folderId: string | null | undefined,
): Promise<boolean> {
  if (!folderId) return false;
  const row = await db.prepare('SELECT id FROM note_folders WHERE id = ? AND campaign_id = ? AND user_id = ?')
    .bind(folderId, campaignId, userId)
    .first<{ id: string }>();
  return row !== null;
}
