/**
 * Dice Logic
 *
 * Pure functions for dice rolling and result creation.
 * Supports local rolling (client-side), manual entry (physical dice),
 * and integration with server-authoritative rolls.
 *
 * @example
 * import { DiceLogic } from '@anvil/data';
 *
 * // Roll 2d10 for a power roll
 * const result = DiceLogic.powerRoll(3); // +3 modifier
 * console.log(result.finalTotal, result.tier);
 *
 * // Manual entry from physical dice
 * const manualResult = DiceLogic.manualResult(14);
 * console.log(manualResult.tier); // 2
 *
 * // Roll arbitrary notation
 * const damageRoll = DiceLogic.rollNotation('2d6+3');
 */

import * as RollLogic from './roll-logic.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * How the roll was generated.
 * - 'local': Generated by DiceLogic (client-side random)
 * - 'manual': Entered by Director (physical dice)
 * - 'server': From server-authoritative system
 */
export type DiceRollSource = 'local' | 'manual' | 'server';

/**
 * Result of a dice roll.
 */
export interface DiceRollResult {
  /** Dice notation that was rolled (e.g., "2d10", "1d6+3") */
  notation: string;
  /** Individual die results (empty for manual entry) */
  rolls: number[];
  /** Sum of dice only */
  total: number;
  /** Modifier applied to roll */
  modifier: number;
  /** Final result (total + modifier) */
  finalTotal: number;
  /** Tier for power rolls (undefined for non-power rolls) */
  tier?: 1 | 2 | 3;
  /** How this roll was generated */
  source: DiceRollSource;
}

/**
 * Parsed dice notation.
 */
export interface ParsedNotation {
  /** Number of dice to roll */
  count: number;
  /** Number of sides per die */
  sides: number;
  /** Modifier to add/subtract */
  modifier: number;
}

// ---------------------------------------------------------------------------
// Random Number Generation
// ---------------------------------------------------------------------------

/**
 * Check if Web Crypto API is available.
 */
function hasCrypto(): boolean {
  return (
    typeof globalThis !== 'undefined' &&
    globalThis.crypto !== undefined &&
    typeof globalThis.crypto.getRandomValues === 'function'
  );
}

/**
 * Generate a cryptographically secure random integer in range [min, max].
 * Falls back to Math.random if crypto is unavailable.
 */
function secureRandomInt(min: number, max: number): number {
  const range = max - min + 1;

  if (hasCrypto()) {
    // Use rejection sampling for unbiased results
    const bytesNeeded = Math.ceil(Math.log2(range) / 8) || 1;
    const maxValid = Math.floor(256 ** bytesNeeded / range) * range - 1;

    let value: number;
    const array = new Uint8Array(bytesNeeded);

    do {
      globalThis.crypto.getRandomValues(array);
      value = array.reduce((acc, byte, i) => acc + byte * 256 ** i, 0);
    } while (value > maxValid);

    return min + (value % range);
  }

  // Fallback to Math.random (less secure but works everywhere)
  return min + Math.floor(Math.random() * range);
}

// ---------------------------------------------------------------------------
// Core Rolling Functions
// ---------------------------------------------------------------------------

/**
 * Roll a single die.
 *
 * @param sides - Number of sides on the die (e.g., 6 for d6, 10 for d10)
 * @returns Random value from 1 to sides inclusive
 *
 * @example
 * const d6 = DiceLogic.rollDie(6);  // 1-6
 * const d10 = DiceLogic.rollDie(10); // 1-10
 */
export function rollDie(sides: number): number {
  if (sides < 1 || !Number.isInteger(sides)) {
    throw new Error(`DiceLogic.rollDie: sides must be a positive integer, got ${sides}`);
  }
  return secureRandomInt(1, sides);
}

/**
 * Roll multiple dice of the same type.
 *
 * @param count - Number of dice to roll
 * @param sides - Number of sides per die
 * @returns Array of individual die results
 *
 * @example
 * const dice = DiceLogic.rollDice(2, 10); // Roll 2d10
 * const sum = dice.reduce((a, b) => a + b, 0);
 */
export function rollDice(count: number, sides: number): number[] {
  if (count < 1 || !Number.isInteger(count)) {
    throw new Error(`DiceLogic.rollDice: count must be a positive integer, got ${count}`);
  }
  return Array.from({ length: count }, () => rollDie(sides));
}

// ---------------------------------------------------------------------------
// Power Roll (2d10)
// ---------------------------------------------------------------------------

/**
 * Execute a Draw Steel power roll (2d10 + modifier).
 * Automatically calculates tier.
 *
 * @param modifier - Value to add to the roll (characteristic value, bonuses)
 * @returns Complete roll result with tier
 *
 * @example
 * // Basic power roll
 * const result = DiceLogic.powerRoll();
 *
 * // With +3 Might modifier
 * const mightRoll = DiceLogic.powerRoll(3);
 * console.log(mightRoll.tier); // 1, 2, or 3
 */
export function powerRoll(modifier: number = 0): DiceRollResult {
  const rolls = rollDice(2, 10);
  const total = rolls[0]! + rolls[1]!;
  const finalTotal = total + modifier;

  return {
    notation: modifier === 0 ? '2d10' : `2d10${modifier >= 0 ? '+' : ''}${modifier}`,
    rolls,
    total,
    modifier,
    finalTotal,
    tier: RollLogic.getTier(finalTotal),
    source: 'local',
  };
}

// ---------------------------------------------------------------------------
// Specific Die Types
// ---------------------------------------------------------------------------

/**
 * Roll a d3 (1-3).
 * Used for heroic resource generation in Draw Steel.
 *
 * @returns Roll result
 *
 * @example
 * const heroicResource = DiceLogic.rollD3();
 * console.log(heroicResource.finalTotal); // 1, 2, or 3
 */
export function rollD3(): DiceRollResult {
  const roll = rollDie(3);
  return {
    notation: '1d3',
    rolls: [roll],
    total: roll,
    modifier: 0,
    finalTotal: roll,
    source: 'local',
  };
}

/**
 * Roll one or more d6.
 * Used for damage rolls, bleeding, etc.
 *
 * @param count - Number of d6 to roll (default 1)
 * @returns Roll result
 *
 * @example
 * const bleeding = DiceLogic.rollD6(); // 1d6
 * const damage = DiceLogic.rollD6(2);  // 2d6
 */
export function rollD6(count: number = 1): DiceRollResult {
  const rolls = rollDice(count, 6);
  const total = rolls.reduce((sum, r) => sum + r, 0);

  return {
    notation: count === 1 ? '1d6' : `${count}d6`,
    rolls,
    total,
    modifier: 0,
    finalTotal: total,
    source: 'local',
  };
}

/**
 * Roll one or more d10.
 *
 * @param count - Number of d10 to roll (default 1)
 * @returns Roll result
 *
 * @example
 * const initiative = DiceLogic.rollD10(); // 1d10
 */
export function rollD10(count: number = 1): DiceRollResult {
  const rolls = rollDice(count, 10);
  const total = rolls.reduce((sum, r) => sum + r, 0);

  return {
    notation: count === 1 ? '1d10' : `${count}d10`,
    rolls,
    total,
    modifier: 0,
    finalTotal: total,
    source: 'local',
  };
}

// ---------------------------------------------------------------------------
// Notation Parsing
// ---------------------------------------------------------------------------

/**
 * Parse a dice notation string.
 *
 * @param notation - Dice notation (e.g., "2d6", "1d10+3", "3d8-2")
 * @returns Parsed components
 * @throws Error if notation is invalid
 *
 * @example
 * const { count, sides, modifier } = DiceLogic.parseNotation('2d6+3');
 * // count: 2, sides: 6, modifier: 3
 */
export function parseNotation(notation: string): ParsedNotation {
  const match = notation.match(/^(\d+)d(\d+)([+-]\d+)?$/i);
  if (!match) {
    throw new Error(
      `DiceLogic.parseNotation: Invalid notation "${notation}". Expected format like "2d6", "1d10+3", etc.`
    );
  }

  return {
    count: parseInt(match[1]!, 10),
    sides: parseInt(match[2]!, 10),
    modifier: match[3] ? parseInt(match[3], 10) : 0,
  };
}

/**
 * Roll dice from a notation string.
 *
 * @param notation - Dice notation (e.g., "2d6+3")
 * @returns Roll result
 *
 * @example
 * const damage = DiceLogic.rollNotation('2d6+3');
 * console.log(damage.finalTotal); // 5-15
 */
export function rollNotation(notation: string): DiceRollResult {
  const { count, sides, modifier } = parseNotation(notation);
  const rolls = rollDice(count, sides);
  const total = rolls.reduce((sum, r) => sum + r, 0);
  const finalTotal = total + modifier;

  // Add tier if this is a power roll (2d10)
  const isPowerRoll = count === 2 && sides === 10;

  return {
    notation,
    rolls,
    total,
    modifier,
    finalTotal,
    tier: isPowerRoll ? RollLogic.getTier(finalTotal) : undefined,
    source: 'local',
  };
}

// ---------------------------------------------------------------------------
// Manual Entry
// ---------------------------------------------------------------------------

/**
 * Create a roll result from manual entry (for physical dice users).
 * The Director enters the total, and we create a result structure.
 *
 * @param total - The total rolled on physical dice
 * @param notation - What was supposedly rolled (default "2d10" for power rolls)
 * @returns Roll result with source: 'manual'
 *
 * @example
 * // Director rolled 14 on physical 2d10
 * const result = DiceLogic.manualResult(14);
 * console.log(result.tier); // 2
 *
 * // With modifier already applied
 * const withMod = DiceLogic.manualResult(17, '2d10+3');
 */
export function manualResult(total: number, notation: string = '2d10'): DiceRollResult {
  const { count, sides, modifier } = parseNotation(notation);
  const isPowerRoll = count === 2 && sides === 10;

  // The total provided is the finalTotal (including modifier)
  const diceTotal = total - modifier;

  return {
    notation,
    rolls: [], // Unknown individual rolls for manual entry
    total: diceTotal,
    modifier,
    finalTotal: total,
    tier: isPowerRoll ? RollLogic.getTier(total) : undefined,
    source: 'manual',
  };
}

/**
 * Create a roll result from server data.
 * Used to wrap server-authoritative roll results.
 *
 * @param dice - Individual die values from server
 * @param modifier - Modifier applied
 * @param notation - Dice notation
 * @returns Roll result with source: 'server'
 *
 * @example
 * // From server response
 * const result = DiceLogic.serverResult([7, 5], 3, '2d10+3');
 */
export function serverResult(
  dice: number[],
  modifier: number = 0,
  notation: string = '2d10'
): DiceRollResult {
  const total = dice.reduce((sum, d) => sum + d, 0);
  const finalTotal = total + modifier;

  const { count, sides } = parseNotation(notation);
  const isPowerRoll = count === 2 && sides === 10;

  return {
    notation,
    rolls: dice,
    total,
    modifier,
    finalTotal,
    tier: isPowerRoll ? RollLogic.getTier(finalTotal) : undefined,
    source: 'server',
  };
}

// ---------------------------------------------------------------------------
// Utility Functions
// ---------------------------------------------------------------------------

/**
 * Check if a roll result has a tier (is a power roll).
 */
export function hasTier(result: DiceRollResult): result is DiceRollResult & { tier: 1 | 2 | 3 } {
  return result.tier !== undefined;
}

/**
 * Get tier description for display.
 */
export function getTierLabel(tier: 1 | 2 | 3): string {
  return RollLogic.getTierDescription(tier);
}

/**
 * Get tier color CSS variable.
 */
export function getTierColorVar(tier: 1 | 2 | 3): string {
  return RollLogic.getTierColorVar(tier);
}

/**
 * Get tier color class for Tailwind.
 */
export function getTierColorClass(tier: 1 | 2 | 3): string {
  return RollLogic.getTierColorClass(tier);
}

/**
 * Format a roll result for display.
 *
 * @example
 * const result = DiceLogic.powerRoll(3);
 * console.log(DiceLogic.formatResult(result));
 * // "7 + 5 + 3 = 15 (Tier 2)"
 */
export function formatResult(result: DiceRollResult): string {
  const parts: string[] = [];

  if (result.rolls.length > 0) {
    parts.push(result.rolls.join(' + '));
  } else {
    parts.push(String(result.total));
  }

  if (result.modifier !== 0) {
    parts.push(result.modifier > 0 ? `+ ${result.modifier}` : `- ${Math.abs(result.modifier)}`);
  }

  let formatted = parts.join(' ') + ` = ${result.finalTotal}`;

  if (result.tier !== undefined) {
    formatted += ` (Tier ${result.tier})`;
  }

  return formatted;
}
