import { useRef, useEffect } from 'react';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@anvil/ui';
import { FilePlus, FolderPlus, Pencil, Trash2 } from 'lucide-react';

export interface ContextMenuState {
  x: number;
  y: number;
  type: 'folder' | 'note';
  id: string;
  isAutoGenerated: boolean;
}

interface NoteContextMenuProps {
  state: ContextMenuState | null;
  onClose: () => void;
  onNewNote: (folderId: string) => void;
  onNewSubfolder: (parentFolderId: string) => void;
  onRename: (id: string, type: 'folder' | 'note') => void;
  onDelete: (id: string, type: 'folder' | 'note') => void;
}

export function NoteContextMenu({
  state,
  onClose,
  onNewNote,
  onNewSubfolder,
  onRename,
  onDelete,
}: NoteContextMenuProps) {
  const triggerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (state && triggerRef.current) {
      triggerRef.current.click();
    }
  }, [state]);

  if (!state) return null;

  return (
    <DropdownMenu open={!!state} onOpenChange={(open) => !open && onClose()}>
      <DropdownMenuTrigger asChild>
        <div
          ref={triggerRef}
          className="pointer-events-none fixed"
          style={{ left: state.x, top: state.y }}
        />
      </DropdownMenuTrigger>
      <DropdownMenuContent align="start" className="w-48">
        {state.type === 'folder' && (
          <>
            <DropdownMenuItem onClick={() => onNewNote(state.id)}>
              <FilePlus className="mr-2 size-4" />
              New Note
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onNewSubfolder(state.id)}>
              <FolderPlus className="mr-2 size-4" />
              New Subfolder
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              disabled={state.isAutoGenerated}
              onClick={() => onRename(state.id, 'folder')}
            >
              <Pencil className="mr-2 size-4" />
              Rename
            </DropdownMenuItem>
            <DropdownMenuItem
              disabled={state.isAutoGenerated}
              className="text-red-400 focus:text-red-400"
              onClick={() => onDelete(state.id, 'folder')}
            >
              <Trash2 className="mr-2 size-4" />
              Delete
            </DropdownMenuItem>
          </>
        )}
        {state.type === 'note' && (
          <>
            <DropdownMenuItem onClick={() => onRename(state.id, 'note')}>
              <Pencil className="mr-2 size-4" />
              Rename
            </DropdownMenuItem>
            <DropdownMenuItem
              className="text-red-400 focus:text-red-400"
              onClick={() => onDelete(state.id, 'note')}
            >
              <Trash2 className="mr-2 size-4" />
              Delete
            </DropdownMenuItem>
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
