import { useState, useCallback, useRef, useMemo, type ReactNode } from 'react';
import { Search, FilePlus, FolderPlus, GripVertical } from 'lucide-react';
import {
  DndContext,
  DragOverlay,
  PointerSensor,
  useSensor,
  useSensors,
  closestCenter,
  type DragStartEvent,
  type DragEndEvent,
  type DragOverEvent,
} from '@dnd-kit/core';
import { useSortable, SortableContext, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import {
  Button,
  Input,
  ScrollArea,
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
  cn,
} from '@anvil/ui';
import type { NoteFolder, Note } from '@anvil/types';
import {
  FileTreeRoot,
  FileTreeFolder,
  FileTreeFile,
} from '../builder/FileTree.js';
import { NoteContextMenu, type ContextMenuState } from './NoteContextMenu.js';
import { NoteSearchResults } from './NoteSearchResults.js';
import { useNotesStore } from '../../stores/notesStore.js';

interface Campaign {
  id: string;
  name: string;
}

interface NoteTreeSidebarProps {
  campaigns: Campaign[];
  selectedCampaignId: string | null;
  onCampaignChange: (id: string) => void;
}

// ── Tree Building ──

interface TreeNode {
  folder: NoteFolder;
  children: TreeNode[];
  notes: Note[];
}

function buildTree(folders: NoteFolder[], notes: Note[]): TreeNode[] {
  const folderMap = new Map<string, TreeNode>();
  for (const f of folders) {
    folderMap.set(f.id, { folder: f, children: [], notes: [] });
  }

  const roots: TreeNode[] = [];
  for (const node of folderMap.values()) {
    if (node.folder.parentFolderId) {
      const parent = folderMap.get(node.folder.parentFolderId);
      if (parent) {
        parent.children.push(node);
      } else {
        roots.push(node);
      }
    } else {
      roots.push(node);
    }
  }

  for (const note of notes) {
    const folder = folderMap.get(note.folderId);
    if (folder) {
      folder.notes.push(note);
    }
  }

  function sortNode(node: TreeNode) {
    node.children.sort((a, b) => a.folder.sortOrder - b.folder.sortOrder);
    node.notes.sort((a, b) => a.sortOrder - b.sortOrder);
    node.children.forEach(sortNode);
  }
  roots.sort((a, b) => a.folder.sortOrder - b.folder.sortOrder);
  roots.forEach(sortNode);

  return roots;
}

// ── Flat item list for DnD ordering ──

interface FlatItem {
  id: string;
  type: 'folder' | 'note';
  depth: number;
  parentFolderId: string | null;
  folderId?: string; // for notes: which folder they belong to
  label: string;
  isAutoGenerated: boolean;
}

function flattenTree(tree: TreeNode[], depth: number = 0): FlatItem[] {
  const items: FlatItem[] = [];
  for (const node of tree) {
    items.push({
      id: node.folder.id,
      type: 'folder',
      depth,
      parentFolderId: node.folder.parentFolderId,
      label: node.folder.name,
      isAutoGenerated: node.folder.isAutoGenerated,
    });
    // Recursively add children
    items.push(...flattenTree(node.children, depth + 1));
    // Add notes in this folder
    for (const note of node.notes) {
      items.push({
        id: note.id,
        type: 'note',
        depth: depth + 1,
        parentFolderId: null,
        folderId: note.folderId,
        label: note.title,
        isAutoGenerated: false,
      });
    }
  }
  return items;
}

// Check if targetId is a descendant of folderId
function isDescendant(folders: NoteFolder[], folderId: string, targetId: string): boolean {
  const children = folders.filter((f) => f.parentFolderId === folderId);
  for (const child of children) {
    if (child.id === targetId) return true;
    if (isDescendant(folders, child.id, targetId)) return true;
  }
  return false;
}

// ── Sortable Item Wrapper ──

interface SortableTreeItemProps {
  item: FlatItem;
  children: ReactNode;
  isDragOverlay?: boolean;
}

function SortableTreeItem({ item, children, isDragOverlay }: SortableTreeItemProps) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: item.id, data: item });

  const style = {
    transform: CSS.Translate.toString(transform),
    transition,
    opacity: isDragging ? 0.4 : 1,
  };

  return (
    <div
      ref={setNodeRef}
      style={isDragOverlay ? undefined : style}
      className={cn('group relative', isDragOverlay && 'rounded-md bg-zinc-800 shadow-lg')}
    >
      {/* Drag handle */}
      <div
        className="absolute left-0 top-1/2 z-10 -translate-y-1/2 cursor-grab opacity-0 transition-opacity group-hover:opacity-100 active:cursor-grabbing"
        style={{ left: `${item.depth * 12 + 2}px` }}
        {...attributes}
        {...listeners}
      >
        <GripVertical className="size-3 text-zinc-600" />
      </div>
      {children}
    </div>
  );
}

// ── Main Sidebar ──

export function NoteTreeSidebar({
  campaigns,
  selectedCampaignId,
  onCampaignChange,
}: NoteTreeSidebarProps) {
  const {
    folders,
    notes,
    selectedNoteId,
    searchResults,
    searchQuery,
    setSelectedNoteId,
    setSelectedFolderId,
    searchNotes,
    clearSearch,
    createFolder,
    createNote,
    updateFolder,
    deleteFolder,
    deleteNote,
    reorderItems,
  } = useNotesStore();

  const [contextMenu, setContextMenu] = useState<ContextMenuState | null>(null);
  const [renamingId, setRenamingId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState('');
  const [activeId, setActiveId] = useState<string | null>(null);
  const [overId, setOverId] = useState<string | null>(null);
  const searchTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const tree = useMemo(() => buildTree(folders, notes), [folders, notes]);
  const flatItems = useMemo(() => flattenTree(tree), [tree]);
  const flatItemIds = useMemo(() => flatItems.map((i) => i.id), [flatItems]);

  // DnD sensors — require 5px movement to start drag (avoids accidental drags on click)
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 5 } }),
  );

  const activeItem = useMemo(
    () => flatItems.find((i) => i.id === activeId) ?? null,
    [flatItems, activeId],
  );

  // ── DnD Handlers ──

  const handleDragStart = useCallback((event: DragStartEvent) => {
    setActiveId(event.active.id as string);
  }, []);

  const handleDragOver = useCallback((event: DragOverEvent) => {
    setOverId(event.over?.id as string | null);
  }, []);

  const handleDragEnd = useCallback(
    (event: DragEndEvent) => {
      setActiveId(null);
      setOverId(null);

      const { active, over } = event;
      if (!over || !selectedCampaignId || active.id === over.id) return;

      const draggedItem = flatItems.find((i) => i.id === active.id);
      const targetItem = flatItems.find((i) => i.id === over.id);
      if (!draggedItem || !targetItem) return;

      // Prevent dropping folder into its own descendant
      if (draggedItem.type === 'folder' && targetItem.type === 'folder') {
        if (isDescendant(folders, draggedItem.id, targetItem.id)) return;
      }

      // Determine what kind of operation this is
      if (draggedItem.type === 'note' && targetItem.type === 'folder') {
        // Moving a note INTO a folder — change folderId
        const targetFolderNotes = notes
          .filter((n) => n.folderId === targetItem.id)
          .sort((a, b) => a.sortOrder - b.sortOrder);
        const newSortOrder = (targetFolderNotes[targetFolderNotes.length - 1]?.sortOrder ?? -1) + 1;

        reorderItems(selectedCampaignId, {
          items: [{ id: draggedItem.id, sortOrder: newSortOrder, folderId: targetItem.id }],
        });
      } else if (draggedItem.type === 'folder' && targetItem.type === 'folder') {
        // Reorder folders at the same level, or move into a different parent
        const draggedFolder = folders.find((f) => f.id === draggedItem.id);
        const targetFolder = folders.find((f) => f.id === targetItem.id);
        if (!draggedFolder || !targetFolder) return;

        // If same parent: reorder siblings
        if (draggedFolder.parentFolderId === targetFolder.parentFolderId) {
          const siblings = folders
            .filter((f) => f.parentFolderId === draggedFolder.parentFolderId && f.id !== draggedItem.id)
            .sort((a, b) => a.sortOrder - b.sortOrder);

          const targetIdx = siblings.findIndex((f) => f.id === targetItem.id);
          siblings.splice(targetIdx, 0, draggedFolder);

          reorderItems(selectedCampaignId, {
            items: siblings.map((f, i) => ({
              id: f.id,
              sortOrder: i,
              parentFolderId: f.parentFolderId,
            })),
          });
        } else {
          // Move folder into target folder as a child
          const targetChildren = folders
            .filter((f) => f.parentFolderId === targetItem.id)
            .sort((a, b) => a.sortOrder - b.sortOrder);
          const newSortOrder = (targetChildren[targetChildren.length - 1]?.sortOrder ?? -1) + 1;

          reorderItems(selectedCampaignId, {
            items: [{ id: draggedItem.id, sortOrder: newSortOrder, parentFolderId: targetItem.id }],
          });
        }
      } else if (draggedItem.type === 'note' && targetItem.type === 'note') {
        // Reorder notes within the same folder
        const draggedNote = notes.find((n) => n.id === draggedItem.id);
        const targetNote = notes.find((n) => n.id === targetItem.id);
        if (!draggedNote || !targetNote) return;

        if (draggedNote.folderId === targetNote.folderId) {
          // Same folder: reorder
          const siblings = notes
            .filter((n) => n.folderId === draggedNote.folderId && n.id !== draggedItem.id)
            .sort((a, b) => a.sortOrder - b.sortOrder);

          const targetIdx = siblings.findIndex((n) => n.id === targetItem.id);
          siblings.splice(targetIdx, 0, draggedNote);

          reorderItems(selectedCampaignId, {
            items: siblings.map((n, i) => ({
              id: n.id,
              sortOrder: i,
              folderId: n.folderId,
            })),
          });
        } else {
          // Different folder: move note to target's folder at target's position
          const targetSiblings = notes
            .filter((n) => n.folderId === targetNote.folderId && n.id !== draggedItem.id)
            .sort((a, b) => a.sortOrder - b.sortOrder);

          const targetIdx = targetSiblings.findIndex((n) => n.id === targetItem.id);
          targetSiblings.splice(targetIdx, 0, { ...draggedNote, folderId: targetNote.folderId });

          reorderItems(selectedCampaignId, {
            items: targetSiblings.map((n, i) => ({
              id: n.id,
              sortOrder: i,
              folderId: targetNote.folderId,
            })),
          });
        }
      }
    },
    [flatItems, folders, notes, selectedCampaignId, reorderItems],
  );

  const handleDragCancel = useCallback(() => {
    setActiveId(null);
    setOverId(null);
  }, []);

  // ── Existing Handlers ──

  const handleSearch = useCallback(
    (value: string) => {
      if (searchTimeoutRef.current) clearTimeout(searchTimeoutRef.current);
      if (!value.trim()) {
        clearSearch();
        return;
      }
      searchTimeoutRef.current = setTimeout(() => {
        if (selectedCampaignId) {
          searchNotes(selectedCampaignId, value);
        }
      }, 300);
    },
    [selectedCampaignId, searchNotes, clearSearch],
  );

  const handleContextMenu = useCallback(
    (e: React.MouseEvent, id: string, type: 'folder' | 'note', isAutoGenerated: boolean) => {
      e.preventDefault();
      setContextMenu({ x: e.clientX, y: e.clientY, type, id, isAutoGenerated });
    },
    [],
  );

  const handleNewNote = useCallback(
    async (folderId: string) => {
      if (!selectedCampaignId) return;
      setContextMenu(null);
      try {
        await createNote(selectedCampaignId, { title: 'Untitled', folderId });
      } catch {
        // Store handles error
      }
    },
    [selectedCampaignId, createNote],
  );

  const handleNewSubfolder = useCallback(
    async (parentFolderId: string) => {
      if (!selectedCampaignId) return;
      setContextMenu(null);
      try {
        const folder = await createFolder(selectedCampaignId, {
          name: 'New Folder',
          parentFolderId,
        });
        setRenamingId(folder.id);
        setRenameValue(folder.name);
      } catch {
        // Store handles error
      }
    },
    [selectedCampaignId, createFolder],
  );

  const handleRename = useCallback(
    (id: string, type: 'folder' | 'note') => {
      setContextMenu(null);
      const item =
        type === 'folder' ? folders.find((f) => f.id === id) : notes.find((n) => n.id === id);
      if (item) {
        setRenamingId(id);
        setRenameValue('title' in item ? item.title : item.name);
      }
    },
    [folders, notes],
  );

  const handleRenameSubmit = useCallback(
    async (id: string, type: 'folder' | 'note') => {
      if (!selectedCampaignId || !renameValue.trim()) {
        setRenamingId(null);
        return;
      }
      try {
        if (type === 'folder') {
          await updateFolder(selectedCampaignId, id, { name: renameValue.trim() });
        } else {
          const { updateNote } = useNotesStore.getState();
          await updateNote(selectedCampaignId, id, { title: renameValue.trim() });
        }
      } catch {
        // Store handles error
      }
      setRenamingId(null);
    },
    [selectedCampaignId, renameValue, updateFolder],
  );

  const handleDelete = useCallback(
    async (id: string, type: 'folder' | 'note') => {
      if (!selectedCampaignId) return;
      setContextMenu(null);
      try {
        if (type === 'folder') {
          await deleteFolder(selectedCampaignId, id);
        } else {
          await deleteNote(selectedCampaignId, id);
        }
      } catch {
        // Store handles error
      }
    },
    [selectedCampaignId, deleteFolder, deleteNote],
  );

  const handleTreeSelect = useCallback(
    (id: string) => {
      if (notes.some((n) => n.id === id)) {
        setSelectedNoteId(id);
      } else {
        setSelectedFolderId(id);
      }
    },
    [notes, setSelectedNoteId, setSelectedFolderId],
  );

  const handleNewTopLevelNote = useCallback(async () => {
    const firstFolder = folders[0];
    if (!selectedCampaignId || !firstFolder) return;
    try {
      await createNote(selectedCampaignId, { title: 'Untitled', folderId: firstFolder.id });
    } catch {
      // Store handles error
    }
  }, [selectedCampaignId, folders, createNote]);

  const handleNewTopLevelFolder = useCallback(async () => {
    if (!selectedCampaignId) return;
    try {
      const folder = await createFolder(selectedCampaignId, { name: 'New Folder' });
      setRenamingId(folder.id);
      setRenameValue(folder.name);
    } catch {
      // Store handles error
    }
  }, [selectedCampaignId, createFolder]);

  // ── Render Helpers ──

  function renderNode(node: TreeNode, depth: number): ReactNode {
    const isRenaming = renamingId === node.folder.id;
    const isDropTarget = overId === node.folder.id && activeId !== node.folder.id;

    return (
      <SortableTreeItem
        key={node.folder.id}
        item={{
          id: node.folder.id,
          type: 'folder',
          depth,
          parentFolderId: node.folder.parentFolderId,
          label: node.folder.name,
          isAutoGenerated: node.folder.isAutoGenerated,
        }}
      >
        <div onContextMenu={(e) => handleContextMenu(e, node.folder.id, 'folder', node.folder.isAutoGenerated)}>
          {isRenaming ? (
            <div className="px-2 py-1" style={{ paddingLeft: `${depth * 12 + 8}px` }}>
              <Input
                autoFocus
                value={renameValue}
                onChange={(e) => setRenameValue(e.target.value)}
                onBlur={() => handleRenameSubmit(node.folder.id, 'folder')}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') handleRenameSubmit(node.folder.id, 'folder');
                  if (e.key === 'Escape') setRenamingId(null);
                }}
                className="h-7 text-sm"
              />
            </div>
          ) : (
            <div className={cn(isDropTarget && 'rounded-md ring-1 ring-blue-500/50')}>
              <FileTreeFolder
                id={node.folder.id}
                label={node.folder.name}
                depth={depth}
                defaultOpen={node.folder.isAutoGenerated}
              >
                {node.children.map((child) => renderNode(child, depth + 1))}
                {node.notes.map((note) => renderNoteItem(note, depth + 1))}
              </FileTreeFolder>
            </div>
          )}
        </div>
      </SortableTreeItem>
    );
  }

  function renderNoteItem(note: Note, depth: number): ReactNode {
    const isRenaming = renamingId === note.id;

    return (
      <SortableTreeItem
        key={note.id}
        item={{
          id: note.id,
          type: 'note',
          depth,
          parentFolderId: null,
          folderId: note.folderId,
          label: note.title,
          isAutoGenerated: false,
        }}
      >
        <div onContextMenu={(e) => handleContextMenu(e, note.id, 'note', false)}>
          {isRenaming ? (
            <div className="px-2 py-1" style={{ paddingLeft: `${depth * 12 + 28}px` }}>
              <Input
                autoFocus
                value={renameValue}
                onChange={(e) => setRenameValue(e.target.value)}
                onBlur={() => handleRenameSubmit(note.id, 'note')}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') handleRenameSubmit(note.id, 'note');
                  if (e.key === 'Escape') setRenamingId(null);
                }}
                className="h-7 text-sm"
              />
            </div>
          ) : (
            <FileTreeFile id={note.id} label={note.title} depth={depth} />
          )}
        </div>
      </SortableTreeItem>
    );
  }

  const isSearching = searchResults !== null;

  return (
    <div className="flex w-64 shrink-0 flex-col border-r border-zinc-800 bg-zinc-950">
      {/* Campaign selector */}
      <div className="border-b border-zinc-800 p-2">
        <Select value={selectedCampaignId ?? ''} onValueChange={onCampaignChange}>
          <SelectTrigger className="h-8 text-sm">
            <SelectValue placeholder="Select campaign" />
          </SelectTrigger>
          <SelectContent>
            {campaigns.map((c) => (
              <SelectItem key={c.id} value={c.id}>
                {c.name}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Search */}
      <div className="border-b border-zinc-800 p-2">
        <div className="relative">
          <Search className="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-zinc-500" />
          <Input
            placeholder="Search notes..."
            value={searchQuery}
            onChange={(e) => handleSearch(e.target.value)}
            className="h-8 pl-8 text-sm"
          />
        </div>
      </div>

      {/* Tree / Search Results */}
      <ScrollArea className="flex-1">
        <div className="p-1">
          {isSearching ? (
            <NoteSearchResults
              results={searchResults}
              folders={folders}
              selectedNoteId={selectedNoteId}
              searchQuery={searchQuery}
              onSelect={(id) => {
                setSelectedNoteId(id);
                clearSearch();
              }}
            />
          ) : (
            <DndContext
              sensors={sensors}
              collisionDetection={closestCenter}
              onDragStart={handleDragStart}
              onDragOver={handleDragOver}
              onDragEnd={handleDragEnd}
              onDragCancel={handleDragCancel}
            >
              <SortableContext items={flatItemIds} strategy={verticalListSortingStrategy}>
                <FileTreeRoot
                  selectedId={selectedNoteId}
                  onSelect={handleTreeSelect}
                >
                  {tree.map((node) => renderNode(node, 0))}
                </FileTreeRoot>
              </SortableContext>

              {/* Drag overlay — shows a floating preview of the dragged item */}
              <DragOverlay dropAnimation={null}>
                {activeItem ? (
                  <div className="rounded-md bg-zinc-800 px-3 py-1.5 text-sm text-zinc-200 shadow-lg">
                    {activeItem.label}
                  </div>
                ) : null}
              </DragOverlay>
            </DndContext>
          )}
        </div>
      </ScrollArea>

      {/* Footer actions */}
      {!isSearching && selectedCampaignId && (
        <div className="flex gap-1 border-t border-zinc-800 p-2">
          <Button
            variant="ghost"
            size="sm"
            className="flex-1 justify-start gap-1.5 text-xs text-zinc-500"
            onClick={handleNewTopLevelNote}
          >
            <FilePlus className="size-3.5" />
            Note
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="flex-1 justify-start gap-1.5 text-xs text-zinc-500"
            onClick={handleNewTopLevelFolder}
          >
            <FolderPlus className="size-3.5" />
            Folder
          </Button>
        </div>
      )}

      {/* Context menu */}
      <NoteContextMenu
        state={contextMenu}
        onClose={() => setContextMenu(null)}
        onNewNote={handleNewNote}
        onNewSubfolder={handleNewSubfolder}
        onRename={handleRename}
        onDelete={handleDelete}
      />
    </div>
  );
}
