import { useEffect, type ReactNode } from 'react';
import { FilePlus, FolderPlus, Pencil, Trash2 } from 'lucide-react';
import { cn } from '@anvil/ui';

export interface ContextMenuState {
  x: number;
  y: number;
  type: 'folder' | 'note';
  id: string;
  isAutoGenerated: boolean;
}

interface NoteContextMenuProps {
  state: ContextMenuState | null;
  onClose: () => void;
  onNewNote: (folderId: string) => void;
  onNewSubfolder: (parentFolderId: string) => void;
  onRename: (id: string, type: 'folder' | 'note') => void;
  onDelete: (id: string, type: 'folder' | 'note') => void;
}

interface MenuActionProps {
  children: ReactNode;
  disabled?: boolean;
  destructive?: boolean;
  onClick: () => void;
}

function MenuAction({ children, disabled, destructive, onClick }: MenuActionProps) {
  return (
    <button
      type="button"
      role="menuitem"
      disabled={disabled}
      onClick={onClick}
      className={cn(
        'flex w-full items-center rounded-sm px-2 py-1.5 text-left text-sm outline-none transition-colors',
        'text-zinc-100 hover:bg-zinc-800 focus:bg-zinc-800',
        destructive && 'text-red-400 hover:text-red-400 focus:text-red-400',
        disabled && 'pointer-events-none opacity-50',
      )}
    >
      {children}
    </button>
  );
}

export function NoteContextMenu({
  state,
  onClose,
  onNewNote,
  onNewSubfolder,
  onRename,
  onDelete,
}: NoteContextMenuProps) {
  useEffect(() => {
    if (!state) return undefined;

    const close = () => onClose();
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
    };

    window.addEventListener('pointerdown', close);
    window.addEventListener('resize', close);
    window.addEventListener('scroll', close, true);
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      window.removeEventListener('pointerdown', close);
      window.removeEventListener('resize', close);
      window.removeEventListener('scroll', close, true);
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [state, onClose]);

  if (!state) return null;

  return (
    <div
      role="menu"
      aria-label={state.type === 'folder' ? 'Folder actions' : 'Note actions'}
      className="fixed z-[100] w-48 overflow-hidden rounded-md border border-zinc-700 bg-zinc-900 p-1 text-zinc-100 shadow-xl shadow-black/40"
      style={{ left: state.x, top: state.y }}
      onContextMenu={(event) => event.preventDefault()}
      onPointerDown={(event) => event.stopPropagation()}
    >
      {state.type === 'folder' && (
        <>
          <MenuAction onClick={() => onNewNote(state.id)}>
            <FilePlus className="mr-2 size-4" />
            New Note
          </MenuAction>
          <MenuAction onClick={() => onNewSubfolder(state.id)}>
            <FolderPlus className="mr-2 size-4" />
            New Subfolder
          </MenuAction>
          <div className="-mx-1 my-1 h-px bg-zinc-700" />
          <MenuAction
            disabled={state.isAutoGenerated}
            onClick={() => onRename(state.id, 'folder')}
          >
            <Pencil className="mr-2 size-4" />
            Rename
          </MenuAction>
          <MenuAction
            disabled={state.isAutoGenerated}
            destructive
            onClick={() => onDelete(state.id, 'folder')}
          >
            <Trash2 className="mr-2 size-4" />
            Delete
          </MenuAction>
        </>
      )}

      {state.type === 'note' && (
        <>
          <MenuAction onClick={() => onRename(state.id, 'note')}>
            <Pencil className="mr-2 size-4" />
            Rename
          </MenuAction>
          <MenuAction destructive onClick={() => onDelete(state.id, 'note')}>
            <Trash2 className="mr-2 size-4" />
            Delete
          </MenuAction>
        </>
      )}
    </div>
  );
}
