/** Notes — per-user notebooks with hierarchical folders, scoped to a campaign or personal notebook */

export type NoteScope = 'director' | 'player';

export interface NoteFolder {
  id: string;
  campaignId: string; // Campaign id, or the personal notebook id for personal notes.
  userId: string;
  scope: NoteScope;
  parentFolderId: string | null;
  name: string;
  isAutoGenerated: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface Note {
  id: string;
  campaignId: string; // Campaign id, or the personal notebook id for personal notes.
  userId: string;
  scope: NoteScope;
  folderId: string;
  title: string;
  content: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateNoteFolderInput {
  name: string;
  scope?: NoteScope;
  parentFolderId?: string;
}

export interface UpdateNoteFolderInput {
  name?: string;
  parentFolderId?: string | null;
  sortOrder?: number;
}

export interface CreateNoteInput {
  title: string;
  scope?: NoteScope;
  folderId: string;
  content?: string;
}

export interface UpdateNoteInput {
  title?: string;
  folderId?: string;
  content?: string;
  sortOrder?: number;
}

export interface ReorderNotesInput {
  items: Array<{
    id: string;
    sortOrder: number;
    parentFolderId?: string | null;
    folderId?: string;
  }>;
}
