/** Notes — per-campaign, per-user notebooks with hierarchical folders */

export interface NoteFolder {
  id: string;
  campaignId: string;
  userId: string;
  parentFolderId: string | null;
  name: string;
  isAutoGenerated: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface Note {
  id: string;
  campaignId: string;
  userId: string;
  folderId: string;
  title: string;
  content: string;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateNoteFolderInput {
  name: string;
  parentFolderId?: string;
}

export interface UpdateNoteFolderInput {
  name?: string;
  parentFolderId?: string | null;
  sortOrder?: number;
}

export interface CreateNoteInput {
  title: string;
  folderId: string;
  content?: string;
}

export interface UpdateNoteInput {
  title?: string;
  folderId?: string;
  content?: string;
  sortOrder?: number;
}

export interface ReorderNotesInput {
  items: Array<{
    id: string;
    sortOrder: number;
    parentFolderId?: string | null;
    folderId?: string;
  }>;
}
